# Use our Dockerfile as the base image
image:
  file: .gitpod.Dockerfile

# Open terminals
tasks:
  # Bash terminal for user to use
  - name: Terminal
    # Install code evaluator
    init: composer install && composer phpcsinit
  # Docker terminal to run our Docker containers and let the user see the output
  - name: Docker
    init: |
      docker network create local
      docker-compose up --no-start --build
    command: docker-compose up
    openMode: split-right
  # Additional Terminals
  - name: Laravel Sail
    before: cd university
    init: |
      php -r "file_exists('.env') || copy('.env.example', '.env');"
      composer update
      composer install
      npm install
      npm run dev
      php artisan key:generate
      sail up --no-start --build
    command: sail up
    openMode: tab-after

# Control the exposed ports
ports:
  - port: 7700
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  # MySQL
  - port: 3306
    onOpen: ignore
  # NGINX
  - port: 8080
    onOpen: ignore
  - port: 9080
    onOpen: open-preview
  # Adminer
  - port: 8033
    onOpen: notify
